---
title: "finalcode_eda"
format: html
execute:
  echo: true
  warning: false
  message: false
editor: visual
fig-width: 6
fig-asp: 0.618
fig-align: center
out-width: "70%"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EDA

### preparing

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(reshape2)
library(corrplot)
library(viridis)
library(gridExtra)
library(usmap)
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)

df <- read.csv("FinalData.csv")

# import dataset+log transform
df <- df %>%
  mutate(TotPop_log = log10(TotPop))
str(df)
```

### Data range+check for missing value

```{r}
# check the missing value
colSums(is.na(df))
```

```{r}
# remove the row that contains missing value (Puerto Rico)
df <- na.omit(df)
```

```{r}
# summary statistic table for the 10 social factors
tbl <-
  df %>%
  select(AgingPer, PovPer, DisPer, UnempPer, HICPer, 
         PSEPer, MGR, WhitePer, MHI, TotPop_log) %>%
  summarise(
    across(
      everything(),
      list(
        mean   = ~ mean(.x, na.rm = TRUE),
        sd     = ~ sd(.x, na.rm = TRUE),
        min    = ~ min(.x, na.rm = TRUE),
        q1     = ~ quantile(.x, 0.25, na.rm = TRUE),
        median = ~ median(.x, na.rm = TRUE),
        q3     = ~ quantile(.x, 0.75, na.rm = TRUE),
        max    = ~ max(.x, na.rm = TRUE)
      )
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to      = c("variable", ".value"),
    names_pattern = "^(.*)_(.*)$" ) 

tbl %>%
  kable(caption = "Summary statistics for 10 Social Factors", digits = 2) %>%
  kable_styling(
    # add lines to the table
    bootstrap_options = c("striped", "bordered"),  
    full_width = FALSE,
    position = "center"
  )

```

### Variable Distribution

1.  **Boxplots for each indicator**

```{r warning=FALSE}
df_long <- df %>%
  select(AgingPer, PovPer, DisPer, UnempPer, HICPer,
         PSEPer, MGR, WhitePer, MHI, TotPop_log) %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Value")

ggplot(df_long, aes(x = Variable, y = Value)) +
  geom_boxplot(fill = "#69b3a2", outlier.color = "red") +
  facet_wrap(~ Variable, scales = "free") + 
  theme_minimal(base_size = 10) +
  theme(
    strip.text = element_text(face = "bold", size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title = element_blank()
  ) +
  labs(title = "Boxplots of 10 Healthcare Vulnerability Social Factors")
```

2.  Histogram + Normality Curve + QQ-plot

    ```{r}
    # histogram and normality curve for each factor
    vars <- c("AgingPer","PovPer","DisPer","UnempPer","HICPer",
              "PSEPer","MGR","WhitePer","MHI","TotPop_log")

    plot_list <- lapply(vars, function(v){
      ggplot(df, aes_string(x = v)) +
    geom_histogram(aes(y = ..density..),
                   bins = 20, fill = "#9ecae1", color = "white") +
    stat_function(fun = dnorm,
                  args = list(mean = mean(df[[v]], na.rm = TRUE),
                              sd = sd(df[[v]], na.rm = TRUE)),
                  color = "red", size = 1) +
    theme_minimal(base_size = 15) +
    labs(title = paste("Histogram of", v), x = v, y = "Density")})

    # create 10 plots on one image, use in the report 
    # do.call(grid.arrange, c(plot_list, ncol = 3))

    for (i in seq(1, length(plot_list), by = 2)) {
      grid.arrange(plot_list[[i]],
               plot_list[[i+1]],
               ncol = 2)}

    # QQ-plot for each factor
    vars <- c("AgingPer","PovPer","DisPer","UnempPer","HICPer",
          "PSEPer","MGR","WhitePer","MHI","TotPop_log")

    qq_list <- lapply(vars, function(v){
      ggplot(df, aes_string(sample = v)) +
    stat_qq() +
    stat_qq_line(color = "red") +
    theme_minimal(base_size = 12) +
    labs(
      title = paste("Normal Q-Q Plot of", v),
      x = "Theoretical Quantiles",
      y = "Sample Quantiles"
    )
    })

    # create 10 plots on one image, use in the report 
    # do.call(grid.arrange, c(qq_list, ncol = 3))

    for (i in seq(1, length(qq_list), by = 2)) {
      if (i == length(qq_list)) {
    grid.arrange(qq_list[[i]], ncol = 1)
      } else {
    grid.arrange(qq_list[[i]], qq_list[[i + 1]], ncol = 2)
      }
    }

    ```

3.  outlier

    ```{r}
    # Outlier Detection (IQR method)

    # Function to detect outliers using IQR
    find_outliers <- function(x){
      Q1 <- quantile(x, 0.25, na.rm = TRUE)
      Q3 <- quantile(x, 0.75, na.rm = TRUE)
      IQR <- Q3 - Q1
      lower <- Q1 - 1.5 * IQR
      upper <- Q3 + 1.5 * IQR
      return(x < lower | x > upper)}

    # Apply function and attach state names
    outlier_results <- lapply(vars, function(var){
      mask <- find_outliers(df[[var]])
      # return outlier states
      df$NAME[mask]})

    names(outlier_results) <- vars
    outlier_results
    ```

4.  heatmap

```{r}
vuln_vars <- df %>%
      select(AgingPer, PovPer, DisPer, UnempPer, HICPer,
             PSEPer, MGR, WhitePer, MHI, TotPop_log)

corr_matrix <- round(cor(vuln_vars), 2)

# create the heatmap
corr_melt <- melt(corr_matrix)
corr_melt_upper <- corr_melt %>% 
  filter(as.numeric(Var1) < as.numeric(Var2))
ggplot(corr_melt_upper, aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_viridis(option = "plasma", limits=c(-1,1), name = "Correlation") +
  geom_text(aes(label = value), color = "white", size = 4) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_blank(),
        panel.grid = element_blank()) +
      labs(title = "Correlation Heatmap (Upper Triangle Only)")
```

5.  Geographic Representation (Map)

```{r}
df_map <- df %>% rename(state = NAME)

# Aging Rate 
plot_usmap(data = df_map, values = "AgingPer", color = "white") +
  scale_fill_viridis(option = "plasma", name = "% Age 65+") +
  labs(title = "Aging Population (%) by State") +
  theme(legend.position = "right")
```

```{r}
# Poverty Rate
plot_usmap(data = df_map, values = "PovPer", color = "white") +
  scale_fill_viridis(option = "plasma", name = "Poverty (%)") +
  labs(title = "Poverty Rate by State") +
  theme(legend.position = "right")
```

```{r}
# Disability Rate 
plot_usmap(data = df_map, values = "DisPer", color = "white") +
  scale_fill_viridis(option = "plasma", name = "Disability (%)") +
  labs(title = "Disability Rate by State")
```

```{r}
# Post-Secondary Education Attainment Rate
plot_usmap(data = df_map, values = "PSEPer", color = "white") +
  scale_fill_viridis(option = "plasma", name = "% Post-Secondary") +
  labs(title = "Post-Secondary Education Attainment Rate by State")
```

```{r}
# Median Annual Household Income 
plot_usmap(data = df_map, values = "MHI", color = "white") +
  scale_fill_viridis(option = "plasma", name = "Income per $1,000 ($)") +
  labs(title = "Median Household Income by State") +
  theme(legend.position = "right")
```

```{r}
# Health Insurance Coverage Rate 
plot_usmap(data = df_map, values = "HICPer", color = "white") +
  scale_fill_viridis(option = "plasma", name = "% Insured") +
  labs(title = "Health Insurance Coverage by State")
```